spring:
  application:
    name: online-store-test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""

server:
  port: 8083
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    online_store: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

token:
  signing:
    key: test-signing-key
